---
 - name: copying files to the remote server
   hosts: all
   
   tasks:
    - name: task is to copy files 
      copy: 
       src: /root/test.txt
       dest: /temp/
       owner: vagrant
       mode: ugo=rw
       backup: true 


