---
 - name: user management  
   hosts: all  #this could be IP sepecific or the server group based

   tasks:
   - name: create a user  
     user: 
       name: nidhi          #name of the user 
       comment: new user add
       home: /home/nidhi    #what directory the user comes under 
       shell: /bin/bash     #assign shell for the user like in widows we have user based repos
       groups: nidhi, f1005 #for multiple groups
       state: absent 
       remove: yes #incase we want to delete the user related data as well


